kind: Pod                              
apiVersion: v1                     
metadata:                           
  name: testpod                  
spec:                                    
  containers:                      
    - name: c00                     
      image: ubuntu              
      command: ["/bin/sh"]
          args: ["-c", "sleep 10 && echo Sleep expired > /dev/termination-log"]; done"]
  restartPolicy: Never         # Defaults to Always
